Testing
Signed-off-by: noopur <noopur@intel.com>

diff --git a/.github/workflows/task_runner_basic_e2e.yml b/.github/workflows/task_runner_basic_e2e.yml
--- a/.github/workflows/task_runner_basic_e2e.yml
+++ b/.github/workflows/task_runner_basic_e2e.yml
@@ -182,224 +182,224 @@ jobs:
         with:
           test_type: "With_TLS"
 
-  test_without_tls:
-    name: Without TLS
-    needs: input_selection
-    if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_without_tls'
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_non_tls) }}
-        python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_non_tls) }}
-        exclude: # Keras does not support Python 3.12
-          - model_name: "keras/mnist"
-            python_version: "3.12"
-          - model_name: "keras/jax/mnist"
-            python_version: "3.12"
-          - model_name: "keras/torch/mnist" 
-            python_version: "3.12"
-      fail-fast: false # do not immediately fail if one of the combinations fail
+  # test_without_tls:
+  #   name: Without TLS
+  #   needs: input_selection
+  #   if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_without_tls'
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_non_tls) }}
+  #       python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_non_tls) }}
+  #       exclude: # Keras does not support Python 3.12
+  #         - model_name: "keras/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/jax/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/torch/mnist" 
+  #           python_version: "3.12"
+  #     fail-fast: false # do not immediately fail if one of the combinations fail
 
-    env:
-      MODEL_NAME: ${{ matrix.model_name }}
-      PYTHON_VERSION: ${{ matrix.python_version }}
+  #   env:
+  #     MODEL_NAME: ${{ matrix.model_name }}
+  #     PYTHON_VERSION: ${{ matrix.python_version }}
 
-    steps:
-      - name: Checkout OpenFL repository
-        id: checkout_openfl
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_ID }}
+  #   steps:
+  #     - name: Checkout OpenFL repository
+  #       id: checkout_openfl
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ env.COMMIT_ID }}
 
-      - name: Pre test run
-        uses: ./.github/actions/tr_pre_test_run
-        if: ${{ always() }}
+  #     - name: Pre test run
+  #       uses: ./.github/actions/tr_pre_test_run
+  #       if: ${{ always() }}
 
-      - name: Run Task Runner E2E tests without TLS
-        id: run_tests
-        run: |
-          python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
-          -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
-          --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} --disable_tls
-          echo "Task runner end to end test run completed"
+  #     - name: Run Task Runner E2E tests without TLS
+  #       id: run_tests
+  #       run: |
+  #         python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
+  #         -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
+  #         --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} --disable_tls
+  #         echo "Task runner end to end test run completed"
 
-      - name: Post test run
-        uses: ./.github/actions/tr_post_test_run
-        if: ${{ always() }}
-        with:
-          test_type: "Without_TLS"
+  #     - name: Post test run
+  #       uses: ./.github/actions/tr_post_test_run
+  #       if: ${{ always() }}
+  #       with:
+  #         test_type: "Without_TLS"
 
-  test_without_client_auth:
-    name: Without Client Auth
-    needs: input_selection
-    if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_without_client_auth'
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_no_client_auth) }}
-        python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_no_client_auth) }}
-        exclude: # Keras does not support Python 3.12
-          - model_name: "keras/mnist"
-            python_version: "3.12"
-          - model_name: "keras/jax/mnist"
-            python_version: "3.12"
-          - model_name: "keras/torch/mnist" 
-            python_version: "3.12"
-      fail-fast: false # do not immediately fail if one of the combinations fail
+  # test_without_client_auth:
+  #   name: Without Client Auth
+  #   needs: input_selection
+  #   if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_without_client_auth'
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_no_client_auth) }}
+  #       python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_no_client_auth) }}
+  #       exclude: # Keras does not support Python 3.12
+  #         - model_name: "keras/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/jax/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/torch/mnist" 
+  #           python_version: "3.12"
+  #     fail-fast: false # do not immediately fail if one of the combinations fail
 
-    env:
-      MODEL_NAME: ${{ matrix.model_name }}
-      PYTHON_VERSION: ${{ matrix.python_version }}
+  #   env:
+  #     MODEL_NAME: ${{ matrix.model_name }}
+  #     PYTHON_VERSION: ${{ matrix.python_version }}
 
-    steps:
-      - name: Checkout OpenFL repository
-        id: checkout_openfl
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_ID }}
+  #   steps:
+  #     - name: Checkout OpenFL repository
+  #       id: checkout_openfl
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ env.COMMIT_ID }}
 
-      - name: Pre test run
-        uses: ./.github/actions/tr_pre_test_run
-        if: ${{ always() }}
+  #     - name: Pre test run
+  #       uses: ./.github/actions/tr_pre_test_run
+  #       if: ${{ always() }}
 
-      - name: Run Task Runner E2E tests without TLS
-        id: run_tests
-        run: |
-          python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
-          -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
-          --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} --disable_client_auth
-          echo "Task runner end to end test run completed"
+  #     - name: Run Task Runner E2E tests without TLS
+  #       id: run_tests
+  #       run: |
+  #         python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
+  #         -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
+  #         --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} --disable_client_auth
+  #         echo "Task runner end to end test run completed"
 
-      - name: Post test run
-        uses: ./.github/actions/tr_post_test_run
-        if: ${{ always() }}
-        with:
-          test_type: 'Without_Client_Auth'
+  #     - name: Post test run
+  #       uses: ./.github/actions/tr_post_test_run
+  #       if: ${{ always() }}
+  #       with:
+  #         test_type: 'Without_Client_Auth'
 
-  test_memory_logs:
-    name: With Memory Logs
-    needs: input_selection
-    if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_memory_logs'
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    strategy:
-      matrix:
-        model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_memory_logs) }}
-        python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_memory_logs) }}
-        exclude: # Keras does not support Python 3.12
-          - model_name: "keras/mnist"
-            python_version: "3.12"
-          - model_name: "keras/jax/mnist"
-            python_version: "3.12"
-          - model_name: "keras/torch/mnist" 
-            python_version: "3.12"
-      fail-fast: false # do not immediately fail if one of the combinations fail
+  # test_memory_logs:
+  #   name: With Memory Logs
+  #   needs: input_selection
+  #   if: needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_memory_logs'
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 30
+  #   strategy:
+  #     matrix:
+  #       model_name: ${{ fromJson(needs.input_selection.outputs.selected_models_for_memory_logs) }}
+  #       python_version: ${{ fromJson(needs.input_selection.outputs.selected_python_for_memory_logs) }}
+  #       exclude: # Keras does not support Python 3.12
+  #         - model_name: "keras/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/jax/mnist"
+  #           python_version: "3.12"
+  #         - model_name: "keras/torch/mnist" 
+  #           python_version: "3.12"
+  #     fail-fast: false # do not immediately fail if one of the combinations fail
 
-    env:
-      MODEL_NAME: ${{ matrix.model_name }}
-      PYTHON_VERSION: ${{ matrix.python_version }}
+  #   env:
+  #     MODEL_NAME: ${{ matrix.model_name }}
+  #     PYTHON_VERSION: ${{ matrix.python_version }}
 
-    steps:
-      - name: Checkout OpenFL repository
-        id: checkout_openfl
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_ID }}
+  #   steps:
+  #     - name: Checkout OpenFL repository
+  #       id: checkout_openfl
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ env.COMMIT_ID }}
 
-      - name: Pre test run
-        uses: ./.github/actions/tr_pre_test_run
-        if: ${{ always() }}
+  #     - name: Pre test run
+  #       uses: ./.github/actions/tr_pre_test_run
+  #       if: ${{ always() }}
 
-      - name: Run Task Runner E2E tests with TLS and memory logs
-        id: run_tests
-        run: |
-          python -m pytest -s tests/end_to_end/test_suites/memory_logs_tests.py \
-          -k test_log_memory_usage_basic --model_name ${{ env.MODEL_NAME }} \
-          --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} \
-          --log_memory_usage
-          echo "Task runner memory logs test run completed"
+  #     - name: Run Task Runner E2E tests with TLS and memory logs
+  #       id: run_tests
+  #       run: |
+  #         python -m pytest -s tests/end_to_end/test_suites/memory_logs_tests.py \
+  #         -k test_log_memory_usage_basic --model_name ${{ env.MODEL_NAME }} \
+  #         --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }} \
+  #         --log_memory_usage
+  #         echo "Task runner memory logs test run completed"
 
-      - name: Post test run
-        uses: ./.github/actions/tr_post_test_run
-        if: ${{ always() }}
-        with:
-          test_type: "With_Memory_Logs"
+  #     - name: Post test run
+  #       uses: ./.github/actions/tr_post_test_run
+  #       if: ${{ always() }}
+  #       with:
+  #         test_type: "With_Memory_Logs"
 
-  test_straggler_check:
-    name: With TLS (torch/mnist_straggler_check, 3.10)
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    if: |
-      (github.event_name == 'schedule' && github.repository_owner == 'securefederatedai') ||
-      (github.event_name == 'workflow_dispatch') ||
-      (github.event.pull_request.draft == false) ||
-      (needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_straggler_check')
+  # test_straggler_check:
+  #   name: With TLS (torch/mnist_straggler_check, 3.10)
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 30
+  #   if: |
+  #     (github.event_name == 'schedule' && github.repository_owner == 'securefederatedai') ||
+  #     (github.event_name == 'workflow_dispatch') ||
+  #     (github.event.pull_request.draft == false) ||
+  #     (needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_straggler_check')
 
-    env:
-      MODEL_NAME: "torch/mnist_straggler_check"
-      PYTHON_VERSION: "3.10"
+  #   env:
+  #     MODEL_NAME: "torch/mnist_straggler_check"
+  #     PYTHON_VERSION: "3.10"
 
-    steps:
-      - name: Checkout OpenFL repository
-        id: checkout_openfl
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_ID }}
+  #   steps:
+  #     - name: Checkout OpenFL repository
+  #       id: checkout_openfl
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ env.COMMIT_ID }}
 
-      - name: Pre test run
-        uses: ./.github/actions/tr_pre_test_run
-        if: ${{ always() }}
+  #     - name: Pre test run
+  #       uses: ./.github/actions/tr_pre_test_run
+  #       if: ${{ always() }}
 
-      - name: Run Straggler Handling Interface Test
-        id: run_tests
-        run: |
-          python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
-          -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
-          --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }}
-          echo "Straggler handling test run completed"
+  #     - name: Run Straggler Handling Interface Test
+  #       id: run_tests
+  #       run: |
+  #         python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
+  #         -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
+  #         --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }}
+  #         echo "Straggler handling test run completed"
 
-      - name: Post test run
-        uses: ./.github/actions/tr_post_test_run
-        if: ${{ always() }}
-        with:
-          test_type: "With_TLS"
+  #     - name: Post test run
+  #       uses: ./.github/actions/tr_post_test_run
+  #       if: ${{ always() }}
+  #       with:
+  #         test_type: "With_TLS"
 
-  test_eden_compression:
-    name: With TLS (torch/mnist_eden_compression, 3.10)
-    runs-on: ubuntu-22.04
-    timeout-minutes: 30
-    if: |
-      (github.event_name == 'schedule' && github.repository_owner == 'securefederatedai') ||
-      (github.event_name == 'workflow_dispatch') ||
-      (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'eden_compression')) || (needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_eden_compression')
+  # test_eden_compression:
+  #   name: With TLS (torch/mnist_eden_compression, 3.10)
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 30
+  #   if: |
+  #     (github.event_name == 'schedule' && github.repository_owner == 'securefederatedai') ||
+  #     (github.event_name == 'workflow_dispatch') ||
+  #     (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'eden_compression')) || (needs.input_selection.outputs.selected_jobs == 'all' || needs.input_selection.outputs.selected_jobs == 'test_eden_compression')
 
-    env:
-      MODEL_NAME: "torch/mnist_eden_compression"
-      PYTHON_VERSION: "3.10"
+  #   env:
+  #     MODEL_NAME: "torch/mnist_eden_compression"
+  #     PYTHON_VERSION: "3.10"
 
-    steps:
-      - name: Checkout OpenFL repository
-        id: checkout_openfl
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ env.COMMIT_ID }}
+  #   steps:
+  #     - name: Checkout OpenFL repository
+  #       id: checkout_openfl
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ env.COMMIT_ID }}
 
-      - name: Pre test run
-        uses: ./.github/actions/tr_pre_test_run
-        if: ${{ always() }}
+  #     - name: Pre test run
+  #       uses: ./.github/actions/tr_pre_test_run
+  #       if: ${{ always() }}
 
-      - name: Run Eden Compression Test
-        id: run_tests
-        run: |
-          python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
-          -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
-          --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }}
-          echo "Eden compression test run completed"
+  #     - name: Run Eden Compression Test
+  #       id: run_tests
+  #       run: |
+  #         python -m pytest -s tests/end_to_end/test_suites/task_runner_tests.py \
+  #         -m task_runner_basic --model_name ${{ env.MODEL_NAME }} \
+  #         --num_rounds ${{ env.NUM_ROUNDS }} --num_collaborators ${{ env.NUM_COLLABORATORS }}
+  #         echo "Eden compression test run completed"
 
-      - name: Post test run
-        uses: ./.github/actions/tr_post_test_run
-        if: ${{ always() }}
-        with:
-          test_type: "With_TLS"
+  #     - name: Post test run
+  #       uses: ./.github/actions/tr_post_test_run
+  #       if: ${{ always() }}
+  #       with:
+  #         test_type: "With_TLS"
