restructure trivy workflow

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -7,10 +7,9 @@ jobs:
   build:
     if: github.event.pull_request.draft == false
     permissions:
-      contents: read # for actions/checkout to fetch code
-      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-      actions: read #  only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-    name: Build
+      contents: read
+      security-events: write
+      actions: read
     runs-on: ubuntu-22.04
     timeout-minutes: 15
     
@@ -18,28 +17,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Build an image from Dockerfile
-        run: |
-          docker build --pull -t docker.io/securefederatedai/openfl:${{ github.sha }} -f openfl-docker/Dockerfile.base .
-
-      - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@0.29.0
-        with:
-          image-ref: 'docker.io/securefederatedai/openfl:${{ github.sha }}'
-          format: 'sarif'
-          output: 'trivy-results.sarif'
-        env:
-          TRIVY_DB_REPOSITORY: 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
-
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: 'trivy-results.sarif'
+      - name: Update package list
+        run: sudo apt update
 
       - name: Install Trivy
         run: |
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
-  
+
       - name: Run Trivy code vulnerability scanner (JSON Output)
         run: |
           trivy --quiet fs \
@@ -47,23 +31,16 @@ jobs:
           --output trivy-code-results.json \
           --ignore-unfixed \
           --vuln-type os,library \
-          --severity CRITICAL,HIGH,MEDIUM,LOW \
+          --severity CRITICAL,HIGH,MEDIUM \
           --db-repository 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db' \
           .
 
-      - name: Display Trivy Scan Results
-        if: failure()  # Ensure this step runs regardless of the previous step's outcome
+      - name: Build an image from Dockerfile
         run: |
-          echo "Trivy Scan Results:"
-          cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
+          docker build --pull -t docker.io/securefederatedai/openfl:${{ github.sha }} -f openfl-docker/Dockerfile.base .
 
-      - name: Upload Code Vulnerability Scan Results
-        uses: actions/upload-artifact@v4
-        with:
-          name: trivy-code-report-json
-          path: trivy-code-results.json
-      
       - name: Run Trivy vulnerability scanner for Docker image (JSON Output)
+        id: trivy-scan
         uses: aquasecurity/trivy-action@0.29.0
         with:
           image-ref: 'docker.io/securefederatedai/openfl:${{ github.sha }}'
@@ -72,16 +49,102 @@ jobs:
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
-          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
+          severity: 'CRITICAL,HIGH,MEDIUM'
           trivyignores: '.trivyignore'
         env:
           TRIVY_DB_REPOSITORY: 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
-  
+
       - name: Display Trivy Scan Results
-        if: failure()  # Ensure this step runs regardless of the previous step's outcome
+        if: failure()
         run: |
-          echo "Trivy Scan Results:"
-          cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
+          if [ -s trivy-docker-results.json ]; then
+            echo "Trivy Scan Results:"
+            cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
+          else
+            echo "Trivy scan results file is empty or not found."
+          fi
+
+      - name: Parse Trivy results and update vulnerable packages
+        id: parse_and_update
+        if: failure()
+        run: |
+          if [ -s trivy-docker-results.json ]; then
+            vulnerable_packages=$(jq -r '.Results[].Vulnerabilities[]? | select(.Severity == "CRITICAL" or .Severity == "HIGH" or .Severity == "MEDIUM") | .PkgName' trivy-docker-results.json | sort -u)
+            echo "vulnerable_packages=$vulnerable_packages" >> $GITHUB_ENV
+            if [ -n "$vulnerable_packages" ]; then
+              for package in $vulnerable_packages; do
+                sudo apt-get install --only-upgrade $package -y || true
+              done
+            else
+              echo "No vulnerable packages found."
+            fi
+          else
+            echo "Trivy scan results file is empty or not found."
+          fi
+
+      - name: Verify package versions
+        if: failure()
+        run: |
+          if [ -n "$vulnerable_packages" ]; then
+            for package in $vulnerable_packages; do
+              dpkg -l | grep $package
+            done
+          else
+            echo "No packages to verify."
+          fi
+
+      - name: Rebuild Docker image after updates
+        if: failure()
+        run: |
+          docker build --pull -t docker.io/securefederatedai/openfl:${{ github.sha }} -f openfl-docker/Dockerfile.base . --no-cache
+
+      - name: Run final Trivy vulnerability scanner for Docker image (JSON Output)
+        if: failure()
+        uses: aquasecurity/trivy-action@0.29.0
+        with:
+          image-ref: 'docker.io/securefederatedai/openfl:${{ github.sha }}'
+          format: 'json'
+          output: 'trivy-final-results.json'
+          exit-code: '1'
+          ignore-unfixed: true
+          vuln-type: 'os,library'
+          severity: 'CRITICAL,HIGH,MEDIUM'
+          trivyignores: '.trivyignore'
+        env:
+          TRIVY_DB_REPOSITORY: 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
+
+      - name: Add unresolved CVEs to .trivyignore
+        if: failure()
+        run: |
+          if [ -s trivy-final-results.json ]; then
+            unresolved_cves=$(jq -r '.Results[].Vulnerabilities[]? | select(.Severity == "CRITICAL" or .Severity == "HIGH" or .Severity == "MEDIUM") | .VulnerabilityID' trivy-final-results.json | sort -u)
+            for cve in $unresolved_cves; do
+              echo $cve >> .trivyignore
+            done
+            git config --global user.email "github-actions[bot]@users.noreply.github.com"
+            git config --global user.name "github-actions[bot]"
+            git add .trivyignore
+            git commit -m "Add unresolved CVEs to .trivyignore"
+            git push
+          else
+            echo "Final Trivy scan results file is empty or not found."
+          fi
+      
+      - name: Display Trivy Scan Results
+        if: failure()
+        run: |
+          if [ -s trivy-docker-results.json ]; then
+            echo "Trivy Scan Results:"
+            cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
+          else
+            echo "Trivy scan results file is empty or not found."
+          fi
+
+      - name: Upload final Trivy scan results
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-final-report-json
+          path: trivy-final-results.json
 
       - name: Upload Docker Vulnerability Scan
         uses: actions/upload-artifact@v4
@@ -96,16 +159,10 @@ jobs:
           --output trivy-code-spdx-results.json \
           --ignore-unfixed \
           --vuln-type os,library \
-          --severity CRITICAL,HIGH,MEDIUM,LOW \
+          --severity CRITICAL,HIGH,MEDIUM \
           --db-repository 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db' \
           .
   
-      - name: Display Trivy Scan Results
-        if: failure()  # Ensure this step runs regardless of the previous step's outcome
-        run: |
-          echo "Trivy Scan Results:"
-          cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
-
       - name: Upload Code Vulnerability Scan Results
         uses: actions/upload-artifact@v4
         with:
@@ -121,17 +178,11 @@ jobs:
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
-          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
+          severity: 'CRITICAL,HIGH,MEDIUM'
           trivyignores: '.trivyignore'
         env:
           TRIVY_DB_REPOSITORY: 'ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db'
     
-      - name: Display Trivy Scan Results
-        if: failure()  # Ensure this step runs regardless of the previous step's outcome
-        run: |
-          echo "Trivy Scan Results:"
-          cat trivy-docker-results.json | jq '.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | {VulnerabilityID, PkgName, InstalledVersion, Severity, Description}'
-
       - name: Upload Docker Vulnerability Scan
         uses: actions/upload-artifact@v4
         with:
